Fix/update bbi flags
metrumresearchgroup/rbabylon pull request #126
Opened 2020-08-27 20:23 UTC by seth127

Implementing #123

2020-08-27 20:30 UTC, seth127 commented
I put a comment here about which flags to update: https://github.com/metrumresearchgroup/rbabylon/issues/123#issuecomment-682173435

Also, it's a little unnecessary and unrelated, but I changed `print_nonmem_args`, `check_nonmem_args` and the constant `NONMEM_ARGS` to their `bbi_` variants for two reasons:

1. It more accurately reflects what they actually do/are. I wrote this very early on and calling them `nonmem_` was just a naive misnomer.
2. It matches the `.bbi_args` argument to various functions, which is what they are related to. Now, if you want to know what you can pass to `.bbi_args` you will call `print_bbi_args()` instead of `print_nonmem_args()`.

2020-08-27 20:31 UTC, seth127 commented
This is currently failing CI because the changed flags reflect changes in the new release of bbi that is necessary for https://github.com/metrumresearchgroup/rbabylon/issues/122 (which has not yet been implemented).

I will circle back to this PR once I implement https://github.com/metrumresearchgroup/rbabylon/issues/122 and everything should pass then.

2020-08-31 15:50 UTC, copernican commented
Why does `check_nonmem_args()` exist? If one of the arguments is invalid, could we instead bubble up the error from the `bbi` call? That would avoid having to keep the list of valid arguments in sync between the two projects.

2020-09-02 14:47 UTC, seth127 commented
I would consider this. One of the main reasons we did this is that bbi used to have a mix of snake_case, dash-case, and camelCase, additionally having the CLI-style `--` or `-` prefix (like `--no-grd-file`) and we wanted to standardize it all to snake_case in R so this was kind of a mapping table.

At this point though, that's probably not needed and we can just change anything that's inconsistent on the bbi side. 

To move forward I would want:

* a defined strategy on argument mapping (dash vs snake)
* an issue in bbi to standardize args accordingly
* an issue in bbi to bubble back more user friendly (and less duplicative/messy) errors

2020-09-14 19:53 UTC, copernican requested changes
Looks good generally, just a few questions/suggestions.

2020-09-14 19:53 UTC, copernican commented on R/aaa.R
>    config = list(type = "character", flag="--config", description = "config file (default is $HOME/babylon.yaml)"),
This does not match the description from 2.3.0:

```sh
➜  ~ /data/apps2/bbi nonmem run --help | grep \\-\\-config
      --config string                       Path (relative or absolute) to another babylon.yaml to load
```

2020-09-14 19:53 UTC, copernican commented on R/modify-model-field.R
> +#' Use `print_bbi_args()` to see a list of valid babylon arguments.
Suggest creating a link.

2020-09-14 19:53 UTC, copernican commented on R/modify-model-field.R
> +#' Use `print_bbi_args()` to see a list of valid babylon arguments.
Suggest creating a link.

2020-09-14 21:32 UTC, copernican approved these changes
LGTM. Should we bump the version? I'm okay if we just wait for the 0.8.0 release.

2020-09-14 21:33 UTC, merged